# Generated by Django 3.2.4 on 2022-05-10 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0010_student_profile_image'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(choices=[('goal', 'Goal'), ('focus', 'Focus')], max_length=16)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.student')),
            ],
            options={
                'ordering': ['student', 'streak_type', 'count', '-datetime'],
            },
        ),
    ]
