# Generated by Django 3.2.4 on 2022-01-27 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_code', models.CharField(max_length=7)),
                ('result_type', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=255)),
                ('subfield', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('points', models.FloatField()),
                ('credits', models.IntegerField()),
                ('version', models.IntegerField()),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1)),
                ('weighting', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('assessment_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=16)),
                ('immutable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('qualification', models.CharField(blank=True, max_length=128, null=True)),
                ('year_level', models.CharField(max_length=128)),
                ('immutable', models.BooleanField(default=True)),
            ],
        ),
    ]
