# Generated by Django 3.2.4 on 2022-04-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_alter_assessment_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='year_level',
            field=models.IntegerField(choices=[(9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12'), (13, 'Year 13')], default=9),
        ),
    ]
