# Generated by Django 3.2.4 on 2022-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_alter_subject_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
