# Generated by Django 3.2.4 on 2022-05-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0007_alter_assessment_assessment_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='weighting',
        ),
    ]
