# Generated by Django 3.2.4 on 2022-05-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0008_remove_assessment_weighting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='points',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='subfield',
            field=models.CharField(max_length=255),
        ),
    ]
