# Generated by Django 3.2.4 on 2022-05-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0009_auto_20220517_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='version',
        ),
    ]
