# Generated by Django 3.2.4 on 2022-01-27 00:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0001_initial'),
        ('group', '0001_initial'),
        ('standards', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verification.verification')),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name', 'email', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_weighting', models.FloatField(default=0.85, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('external_weighting', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('student_id', models.CharField(blank=True, max_length=6, null=True)),
                ('nsn', models.CharField(blank=True, max_length=10, null=True)),
                ('year_level', models.IntegerField(choices=[(9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12'), (13, 'Year 13')], default=9)),
                ('viewing_year_level', models.IntegerField(choices=[(9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12'), (13, 'Year 13')], default=9)),
                ('show_mock_results', models.BooleanField(default=False)),
                ('active_playground_id', models.IntegerField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('grading_system', models.CharField(choices=[('ncea', 'NCEA'), ('alphabetical', 'Alphabetical')], default='ncea', max_length=16)),
                ('is_verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessments', models.ManyToManyField(to='standards.Assessment')),
                ('classes', models.ManyToManyField(to='group.Class')),
                ('color_settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.colorsettings')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.school')),
                ('subjects', models.ManyToManyField(to='standards.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms')], default='mr', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessments', models.ManyToManyField(to='standards.Assessment')),
                ('classes', models.ManyToManyField(to='group.Class')),
                ('color_settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.colorsettings')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.school')),
                ('subjects', models.ManyToManyField(to='standards.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
