# Generated by Django 3.2.4 on 2022-02-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='external_weighting',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internal_weighting',
        ),
    ]
