# Generated by Django 3.2.4 on 2022-04-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
        ('group', '0001_initial'),
        ('usermgmt', '0002_auto_20220201_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assessments',
            field=models.ManyToManyField(blank=True, null=True, to='standards.Assessment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='group.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='standards.Subject'),
        ),
    ]
