# Generated by Django 3.2.4 on 2022-04-21 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_auto_20220418_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
