# Generated by Django 3.2.4 on 2022-04-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0004_student_year_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='external_weighting',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_weighting',
            field=models.FloatField(default=0.85),
        ),
    ]
