# Generated by Django 3.2.4 on 2022-04-26 03:10

from django.db import migrations, models
import django.utils.timezone
import usermgmt.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0007_auto_20220426_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='viewing_year',
            field=models.IntegerField(default=usermgmt.models.get_year),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
