# Generated by Django 3.2.4 on 2022-04-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0008_auto_20220426_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='active_playground_id',
            new_name='recent_playground_id',
        ),
        migrations.AddField(
            model_name='student',
            name='playground_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
