# Generated by Django 3.2.4 on 2022-05-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0010_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='assessments',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='color_settings',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='school',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='SchoolAdmin',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
