# Generated by Django 3.2.4 on 2022-05-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0011_auto_20220513_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
    ]
