# Generated by Django 3.2.4 on 2022-05-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0012_remove_student_classes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatedEmail',
        ),
    ]
