# Generated by Django 3.2.4 on 2022-05-12 21:45

from django.db import migrations, models
import usermgmt.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0013_delete_updatedemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='average',
        ),
        migrations.AlterField(
            model_name='student',
            name='year_joined',
            field=models.IntegerField(default=usermgmt.models.get_year),
        ),
    ]
