# Generated by Django 3.2.4 on 2022-05-13 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0014_auto_20220513_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nsn',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_joined',
        ),
        migrations.AddField(
            model_name='student',
            name='startingdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
