# Generated by Django 3.2.4 on 2022-05-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0016_auto_20220516_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='startingdate',
            new_name='starting_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default='00000'),
        ),
    ]
