# Generated by Django 4.0.6 on 2022-07-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0018_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='internal_weighting',
            field=models.FloatField(default=1),
        ),
    ]
