# Generated by Django 4.0.6 on 2022-07-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0019_alter_student_internal_weighting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assessments',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
