# Generated by Django 3.2.4 on 2022-01-27 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.FloatField()),
                ('field', models.CharField(max_length=255)),
                ('comparitor', models.CharField(choices=[('<', 'less than'), ('<=', 'less than or equal to'), ('>', 'more than'), ('>=', 'more than or equal to'), ('==', 'equal to')], default='>=', max_length=2)),
                ('model_name', models.CharField(choices=[('result.Result', 'result'), ('focus.FocusPeriod', 'focus period')], max_length=255)),
                ('filters', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('success', 'Success'), ('fail', 'Failed')], default='ongoing', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_option', models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='before', max_length=255)),
                ('repeat', models.CharField(choices=[('once', 'Once'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.student')),
            ],
        ),
    ]
