# Generated by Django 3.2.4 on 2022-01-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_goal_is_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='field',
            field=models.CharField(choices=[('assessment.credits', 'Credits'), ('gpa', 'GPA'), ('rankscore', 'Rank Score'), ('duration', 'Focus Hours')], max_length=255),
        ),
    ]
