# Generated by Django 3.2.4 on 2022-01-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0005_alter_goal_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
