# Generated by Django 3.2.4 on 2022-04-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_goalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalrecord',
            name='cycle',
            field=models.IntegerField(default=0),
        ),
    ]
