# Generated by Django 3.2.4 on 2022-05-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0009_auto_20220424_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='current',
            field=models.FloatField(default=0),
        ),
    ]
