# Generated by Django 3.2.4 on 2022-05-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0010_alter_goal_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_priority',
        ),
    ]
