# Generated by Django 3.2.4 on 2022-05-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0011_remove_goal_is_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='field',
            field=models.CharField(choices=[('assessment.credits', 'Credits'), ('gpa', 'GPA'), ('rankscore', 'Rank Score'), ('duration', 'Focus Period')], max_length=255),
        ),
    ]
