# Generated by Django 3.2.4 on 2022-05-09 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0012_alter_goal_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
