# Generated by Django 3.2.4 on 2022-05-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0017_alter_goal_end_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalrecord',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('fail', 'Failed')], default='ongoing', max_length=255),
        ),
    ]
