# Generated by Django 4.0.6 on 2022-07-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0018_alter_goalrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='comparator',
            field=models.CharField(choices=[('>', 'more than'), ('>=', 'more than or equal to'), ('==', 'equal to')], default='>=', max_length=2),
        ),
    ]
