# Generated by Django 4.0.6 on 2022-07-27 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0019_alter_goal_comparator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalrecord',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.goal'),
        ),
    ]
