# Generated by Django 3.2.4 on 2022-01-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verification', '0001_initial'),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('moe_code', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('web_domain', models.CharField(default='', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verification.verification')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('year_level', models.IntegerField(choices=[(9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12'), (13, 'Year 13')], default=9)),
                ('grading_system', models.CharField(choices=[('ncea', 'NCEA'), ('alphabetical', 'Alphabetical')], default='ncea', max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards.subject')),
                ('verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verification.verification')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
