# Generated by Django 3.2.4 on 2022-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='moe_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
