# Generated by Django 3.2.4 on 2022-05-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_delete_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='verification',
        ),
    ]
