# Generated by Django 3.2.4 on 2022-05-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_remove_school_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='completed_first_full_sync',
            field=models.BooleanField(default=False),
        ),
    ]
